clone_depth: 5
environment:
  nodejs_version: "10.15"
platform: x64 # flow needs 64b platforms
# Install scripts. (runs after repo cloning)
install:
  # 1. Yarn 1.2.1 is already preinstalled, so no need to install yarn.
  #- choco install yarn
  # But we need to select the right node
  - ps: Install-Product node $env:nodejs_version $env:platform
  # 2. Setup the project
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - yarn versions
  # run tests
  - yarn license-check
  - yarn lint
  - yarn flow --quiet
  # stop flow to recover some memory
  - yarn flow-stop
  - yarn test
  - yarn build-prod:quiet

cache:
  - node_modules

# Don't actually build.
build: off
